### ISSUE TITLE
Permission denied on db4geonode after docker-compose up

### ISSUE THREAD

**Issue by ldt** [GeoNode/geonode-docker#12]
Hi all,

After installing the 2.8 docker version of geonode on my mac, I get the following error:

db4geonode       | ERROR:  permission denied for relation django_migrations
db4geonode       | STATEMENT:  SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"

Are there some specific configuration changes required before launching docker-compose up?

Thanks for your help,

Laurent

**Comment by afabiani** [comment]
Hi @ldt 
you can maybe take a look at the docker-compose yml (and override) from here

https://github.com/GeoNode/geonode-project

also take a look at the README

**Comment by marcelom56** [comment]
@ldt , I had the same issue that you reported... I don't know if you already solved it, but I will share what I did to solve mine...

Some months ago I tried geonode just for kicks and to run some tests... After I was done with the tests, I removed the containers and forgot to remove the volumes...

Today when I ran geonode again the issue that you reported appeared...

I fixed it by removing the older volumes created on the first try ("docker volume prune" ) and starting again the containers from scratch.

I think that username and / or password changed from the older version to the current version, so when containers go up (using olds volumes), the credentials does not match...

**Comment by ldt** [comment]
Hi @marcelom56, thanks for your insight.
I forgot to close this issue but I solved it by re-running the docker instructions in the right order. I think I had forgotten one of them by reading to quickly the readme.
