### ISSUE TITLE
Problems while installation of geonode using docker : manifest file not found for postgis 

### ISSUE THREAD

**Issue by tayyabsayyad** [GeoNode/geonode-docker#14]
jshah@Geo:~/geonode$   docker-compose -f docker-compose.yml -f docker-compose.override.localhost.yml up --build

Pulling db (geonode/postgis:10)...
ERROR: manifest for geonode/postgis:10 not found

**Comment by afabiani** [comment]
Hi @tayyabsayyad ,
I checked this and noticed that the image on docker named "postgis:10" has not been created.

I have triggered the build. It should be available in few minutes.
