### ISSUE TITLE
GeoServer lacks a tag for the latest image build 

### ISSUE THREAD

**Issue by ridoo** [GeoNode/geonode-docker#35]
GeoNode `v4.2.2` declares to use [docker image `geonode/geoserver:2.23.3-v2`](https://github.com/GeoNode/geonode/blob/4.2.2/docker-compose.yml#L94). However, that image was build via manual trigger and there is a missing tag to later reason on what commit was the source of it. The only way to find out at the moment [is the action run](https://github.com/GeoNode/geonode-docker/actions/runs/7787228796/job/21233887358#step:2:156) to build and push the image. This, however, can be quite cumbersome, especially when people wants to check for older versions (in the future, of course, when more and more actions will exist).

/cc @giohappy I undestand it is quite handy to have such manual triggers, but in such cases (building a tagged version) this makes it harder to follow.

**Comment by giohappy** [comment]
@ridoo you're right, it was a manual trigger and we forgot to create a corresponding tag. I've just created it https://github.com/GeoNode/geonode-docker/releases/tag/geoserver%232.23.3-v2
