### ISSUE TITLE
Missing geonode/geoserver images

### ISSUE THREAD

**Issue by knl88** [GeoNode/geonode-docker#45]
Hi, I wonder what have happened with  [geonode/geoserver  images ](https://hub.docker.com/r/geonode/geoserver/tags) predating v2.23? For example tag 2.20.5, I can't find any  of the older images on docker hub. Corresponding [geonode/geoserver_data](https://hub.docker.com/r/geonode/geoserver_data/tags) tags still exist for older releases like v2.20.5.

**Comment by giohappy** [comment]
@knl88 All past images without the recent CVE fixes were unpublished from Docker.
We're planning to republish a Geoserver 2.23.3  that suits GeoNode < 4.2.0 (after that version we have made changes to the Geoserver image that would break previous versions) which includes the pathed jars.

**Comment by giohappy** [comment]
geonode/geoserver:2.23.3 has been republished. Any GeoNode deployment < 4.2.0 can be updated to use that Geoserver image.

**Comment by knl88** [comment]
Thanks for the update:) Not completely sure 2.23.3 will work flawlessly with geonode 4.0.x, but guess the goal anyway should be to get onto the newest geonode releases.

**Comment by giohappy** [comment]
>Thanks for the update:) Not completely sure 2.23.3 will work flawlessly with geonode 4.0.x

I don't see any problem, but of course you should give it a try before moving it to any production instance.

**Comment by giohappy** [comment]
@knl88 FYI we have republished [Geoserver 2.20.7](https://hub.docker.com/layers/geonode/geoserver/2.20.7/images/sha256-605d6f767352e8fc01ca5a04df032cc4a5e7e804b08f64564940f2c57040faa2) with the fixes for the CVEs.
