### ISSUE TITLE
No need to log to file in uwsgi

### ISSUE THREAD

**Issue by cezio** [GeoNode/geonode-docker#5]
When deployed, container provides output preview with `docker logs`. There's no point to log uwsgi process to file, as it's harder to diagnose problems. This line is not needed:

https://github.com/GeoNode/geonode-docker/blob/master/uwsgi.ini#L4

**Comment by francbartoli** [comment]
@cezio I'm not quite sure the uswgi log is sent to the preview of docker logging. The issue might be it should do that in case it doesn't
